# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 75396e7d4860f152a941acff6086897a240fcbe0d85d965c4d1fa561a0faa5c9312e91221d6ce43969880c5e53258f8845c95630a4176b49fd1b90d4085141ee

test:
  secret_key_base: 4eabd68719885a3803badab55b942485f3def11726d1a707d93b331159c9fff2fd9fd412b2c2caff15574272cbf3f662ce8fb7d44cd373273a0024b465409807

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
